version: '3'
services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=ricpolim
      - POSTGRES_PASSWORD=password
    ports:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - api.network
  api:
    build:
      context: ./
    image: products
    depends_on:
      - db
    ports:
      - 3000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ricpolim
      DB_PASSWORD: password
      DB_NAME: sdc_products
    restart: always
    links:
      - db
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - api.network
    deploy:
      mode: replicated
      replicas: 3
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - api.network
volumes:
  db:
    driver: local
networks:
    api.network: